### ISSUE TITLE
403 Forbidden in the GetAccountInformationAsync()

### ISSUE THREAD

**Issue by memoryfraction** [CryptoDevTV/Algorand-SDK#9]
![image](https://user-images.githubusercontent.com/18358791/193477433-4a41365c-ec17-449d-a786-afc2377bf215.png)
Healtu.Succeed == true, while GetAccountInfo() does not work, can I know how to fix it?

**Comment by memoryfraction** [comment]
More phenomenon, idx2 works for neither
![image](https://user-images.githubusercontent.com/18358791/193478271-45243fa7-ddbc-4aa9-b98e-a6238e0148f1.png)

**Comment by memoryfraction** [comment]
full error message

Exception: Request unsuccessful: 403 (Forbidden) | StackTrace:    at Algorand.Tools.Api.AlgorandApiClient.GetAsync[T](String requestUri) in E:\GitHub\CryptoDevTV.Algorand-SDK\Algorand\Algorand.Tools\Api\IAlgorandApiClient.cs:line 43
   at Algorand.Process.Algod.Client.AlgodClient.GetAccountInformationAsync(String address) in E:\GitHub\CryptoDevTV.Algorand-SDK\Algorand\Algorand.Process.Algod\Client\AlgodClient.cs:line 45

**Comment by memoryfraction** [comment]
fixed: https://github.com/CryptoDevTV/Algorand-SDK/pull/10
